<?php

/**
 * Create an .htaccess file in image style directories that have a change format
 * image effect to enforce the correct Content-Type header for the derivative
 * images.
 */
function image_effects_coloractions_update_7101(&$sandbox) {
  module_load_include('module', 'image');
  include_once dirname(__FILE__) . '/image_effects_coloractions.htaccess_creator.inc';
  image_effects_coloractions_create_htaccess_all_styles();
}
