<?php
/**
 * Implements hook_requirements().
 */
function imagecache_autorotate_requirements(/*$phase*/) {
  $result = array();
  $t = get_t();
  if (!function_exists('exif_read_data')) {
    $result['imagecache_autorotate_exif_extension'] = array(
      'title'=> '',
      'description'=> $t('The exif_read_data() function is not available in this PHP installation. You probably will have to enable the exif extension.'),
      'severity' => REQUIREMENT_WARNING,
    );
  }
  return $result;
}
